// generated by the syntax-highlighting plugin — describes what a lexer
// file must export. Reference it from your lexer with:
//   /** @type {import('./lexer-api').Lexer} */
//   module.exports = { ... };

export type Token = { text: string; type: string };

export type DeclaredColour = { name: string; value: string };

export interface Lexer {
	/** stable namespaced identity, e.g. 'alfred.nasm' — never change between versions */
	id: string;
	/** bump when token types / colours change */
	version?: number;
	/** display name and the default code-block tag (the ```name fence) */
	name: string;
	/** every colour this lexer uses — names are frozen once shipped */
	requiredColours: DeclaredColour[];
	/** token type -> the name of a colour declared in requiredColours */
	colourMapping: Record<string, string>;
	tokenize(input: string): Token[];
}
