import { Lexer } from "./api";

// vault-relative folder (inside the plugin dir) that holds user-imported lexers
export const IMPORTED_LEXERS_DIR = "imported_lexers";

export type FileLexer = { lexer: Lexer, path: string };

// Dev-time type stubs written into the imported lexers folder, so authors get
// editor autocomplete via:  /** @type {import('./lexer-api').Lexer} */
// Purely a dev aid — the runtime contract is validateLexerShape below.
export const LEXER_API_DTS = `// generated by the syntax-highlighting plugin — describes what a lexer
// file must export. Reference it from your lexer with:
//   /** @type {import('./lexer-api').Lexer} */
//   module.exports = { ... };

export type Token = { text: string; type: string };

export type DeclaredColour = { name: string; value: string };

export interface Lexer {
	/** stable namespaced identity, e.g. 'alfred.nasm' — never change between versions */
	id: string;
	/** bump when token types / colours change */
	version?: number;
	/** display name shown in settings — independent of the extension */
	name: string;
	/** default code-block tag (the \`\`\`tag fence); falls back to name when omitted.
	    The user can re-target it in settings. */
	defaultExtension?: string;
	/** every colour this lexer uses — names are frozen once shipped */
	requiredColours: DeclaredColour[];
	/** token type -> the name of a colour declared in requiredColours */
	colourMapping: Record<string, string>;
	tokenize(input: string): Token[];
}
`;

// Structural validation of a lexer module's export — the runtime enforcement
// of the Lexer interface. Returns a human-readable problem, or null if valid.
export function validateLexerShape(obj: any): string | null {
	if (!obj || typeof obj !== 'object') return 'module.exports is not an object';
	if (typeof obj.id !== 'string' || !obj.id) return 'missing string field "id"';
	if (typeof obj.name !== 'string' || !obj.name) return 'missing string field "name"';
	if (obj.defaultExtension !== undefined && (typeof obj.defaultExtension !== 'string' || !obj.defaultExtension)) {
		return '"defaultExtension" must be a non-empty string';
	}
	if (obj.version !== undefined && typeof obj.version !== 'number') return '"version" must be a number';
	if (!Array.isArray(obj.requiredColours)) return 'missing array field "requiredColours"';
	for (const colour of obj.requiredColours) {
		if (!colour || typeof colour.name !== 'string' || typeof colour.value !== 'string') {
			return 'requiredColours entries must be { name: string, value: string }';
		}
	}
	if (!obj.colourMapping || typeof obj.colourMapping !== 'object' || Array.isArray(obj.colourMapping)) {
		return 'missing object field "colourMapping"';
	}
	for (const [tokenType, colourName] of Object.entries(obj.colourMapping)) {
		if (typeof colourName !== 'string') {
			return `colourMapping["${tokenType}"] must be a colour name (string)`;
		}
	}
	if (typeof obj.tokenize !== 'function') return 'missing function "tokenize"';
	return null;
}

// Evaluate a lexer file's source. CommonJS shim via new Function: the code
// sees `module`/`exports` and NOTHING else — no require, no plugin API, no
// Obsidian. Pure data + a tokenize function, which we validate structurally.
// Throws with a descriptive message on syntax/validation errors.
export function evaluateLexerSource(code: string, sourceName: string): Lexer {
	const module = { exports: {} as any };
	let factory: Function;
	try {
		factory = new Function('module', 'exports', code);
	} catch (e) {
		throw new Error(`${sourceName}: syntax error — ${e instanceof Error ? e.message : e}`);
	}
	try {
		factory(module, module.exports);
	} catch (e) {
		throw new Error(`${sourceName}: threw while loading — ${e instanceof Error ? e.message : e}`);
	}
	const lexer = module.exports?.default ?? module.exports;
	const problem = validateLexerShape(lexer);
	if (problem) {
		throw new Error(`${sourceName}: ${problem}`);
	}
	return lexer as Lexer;
}

// Open the OS file browser for a .js file and hand back its content.
// Nothing happens if the user cancels the dialog.
export function pickJsFile(onPick: (code: string, fileName: string) => void): void {
	const input = document.createElement('input');
	input.type = 'file';
	input.accept = '.js';
	input.onchange = async () => {
		const file = input.files?.[0];
		if (!file) return;
		onPick(await file.text(), file.name);
	};
	input.click();
}
