import { Lexer, PaletteColour } from "./api";

// vault-relative folder (inside the plugin dir) that holds user-imported lexers
export const IMPORTED_LEXERS_DIR = "imported_lexers";

// every lexer folder's entry module and palette file
export const LEXER_ENTRY = "index.js";
export function paletteFilePath(lexerFolder: string): string {
	return `${lexerFolder}/palette.json`;
}

// Dev-time type stubs written into the imported lexers folder, so authors get
// editor autocomplete via:  /** @type {import('./lexer-api').Lexer} */
// Purely a dev aid — the runtime contract is validateLexerShape below.
export const LEXER_API_DTS = `// generated by the syntax-highlighting plugin — describes what a lexer
// must export. A lexer is a FOLDER in imported_lexers/ containing:
//   index.js       — the entry module; its exports are the Lexer
//   palette.json   — a PaletteColour[] array; colourMapping names resolve against it
//   *.js           — any other modules, loadable from index.js (and each other)
//                    via require('./relative/path') — relative paths only,
//                    nothing outside the lexer's folder, no node built-ins
//
// Reference this stub from your entry module for autocomplete:
//   /** @type {import('../lexer-api').Lexer} */
//   module.exports = { ... };

export type Token = { text: string; type: string };

/** one entry of the <yourlexer>.palette.json sidecar — names are frozen
    once shipped, they are the reconciliation key across updates */
export type PaletteColour = { name: string; value: string };

export interface Lexer {
	/** stable namespaced identity, e.g. 'alfred.nasm' — never change between versions */
	id: string;
	/** bump when token types / palette change */
	version?: number;
	/** display name shown in settings — independent of the extension */
	name: string;
	/** default code-block tag (the \`\`\`tag fence); falls back to name when omitted.
	    The user can re-target it in settings. */
	defaultExtension?: string;
	/** token type -> the name of a colour in the palette sidecar */
	colourMapping: Record<string, string>;
	tokenize(input: string): Token[];
}
`;

// Structural validation of a lexer module's export — the runtime enforcement
// of the Lexer interface. Returns a human-readable problem, or null if valid.
export function validateLexerShape(obj: any): string | null {
	if (!obj || typeof obj !== 'object') return 'module.exports is not an object';
	if (typeof obj.id !== 'string' || !obj.id) return 'missing string field "id"';
	if (typeof obj.name !== 'string' || !obj.name) return 'missing string field "name"';
	if (obj.defaultExtension !== undefined && (typeof obj.defaultExtension !== 'string' || !obj.defaultExtension)) {
		return '"defaultExtension" must be a non-empty string';
	}
	if (obj.version !== undefined && typeof obj.version !== 'number') return '"version" must be a number';
	if (!obj.colourMapping || typeof obj.colourMapping !== 'object' || Array.isArray(obj.colourMapping)) {
		return 'missing object field "colourMapping"';
	}
	for (const [tokenType, colourName] of Object.entries(obj.colourMapping)) {
		if (typeof colourName !== 'string') {
			return `colourMapping["${tokenType}"] must be a colour name (string)`;
		}
	}
	if (typeof obj.tokenize !== 'function') return 'missing function "tokenize"';
	return null;
}

// Structural validation of a palette's parsed JSON.
export function validatePaletteShape(obj: any): string | null {
	if (!Array.isArray(obj)) return 'palette must be a JSON array of { name, value } entries (or a shop palette with a "colours" array)';
	for (const colour of obj) {
		if (!colour || typeof colour.name !== 'string' || !colour.name || typeof colour.value !== 'string') {
			return 'palette entries must be { name: string, value: string }';
		}
	}
	return null;
}

// Parse and validate a palette's source text: a bare [{ name, value }]
// array, or the shop's palette format ({ id, name, ..., colours: [...] }).
// Throws with a descriptive message on syntax/validation errors.
export function parsePaletteSource(text: string, sourceName: string): PaletteColour[] {
	let parsed: any;
	try {
		parsed = JSON.parse(text);
	} catch (e) {
		throw new Error(`${sourceName}: not valid JSON — ${e instanceof Error ? e.message : e}`);
	}
	const colours = Array.isArray(parsed) ? parsed : parsed?.colours;
	const problem = validatePaletteShape(colours);
	if (problem) {
		throw new Error(`${sourceName}: ${problem}`);
	}
	return colours as PaletteColour[];
}

// marks errors already carrying a "file: reason" prefix, so a failure deep
// in a require chain isn't re-wrapped at every level on the way up
class LexerLoadError extends Error {}

// Evaluate a lexer's modules. CommonJS shim via new Function: each module
// sees `module`/`exports`/`require` and NOTHING else — no plugin API, no
// Obsidian, no node built-ins. `require` resolves relative paths against
// the in-memory module map only, so nothing outside the lexer's folder is
// reachable. Cycles get CommonJS semantics (the partially-built exports).
// `files` maps folder-relative paths ('index.js', 'lib/tables.js') to
// source; evaluation starts at `entry`. Throws with a descriptive message
// on syntax/resolution/validation errors.
export function evaluateLexerModules(files: Record<string, string>, entry: string, sourceName: string): Lexer {
	const cache: Record<string, { exports: any }> = {};

	const resolve = (from: string, spec: string): string => {
		if (!spec.startsWith('./') && !spec.startsWith('../')) {
			throw new LexerLoadError(`${sourceName}/${from}: only relative requires are allowed — got "${spec}"`);
		}
		const parts = from.split('/').slice(0, -1);
		for (const seg of spec.split('/')) {
			if (seg === '' || seg === '.') continue;
			if (seg === '..') {
				if (!parts.length) throw new LexerLoadError(`${sourceName}/${from}: require("${spec}") escapes the lexer folder`);
				parts.pop();
			} else {
				parts.push(seg);
			}
		}
		let path = parts.join('/');
		if (!path.endsWith('.js')) path += '.js';
		if (!(path in files)) {
			throw new LexerLoadError(`${sourceName}/${from}: require("${spec}") — no module "${path}" in the lexer folder`);
		}
		return path;
	};

	const load = (path: string): any => {
		// returns the partially-built exports when hit through a cycle
		if (cache[path]) return cache[path].exports;
		const module = { exports: {} as any };
		cache[path] = module;
		let factory: Function;
		try {
			factory = new Function('module', 'exports', 'require', files[path]);
		} catch (e) {
			throw new LexerLoadError(`${sourceName}/${path}: syntax error — ${e instanceof Error ? e.message : e}`);
		}
		try {
			factory(module, module.exports, (spec: string) => load(resolve(path, spec)));
		} catch (e) {
			if (e instanceof LexerLoadError) throw e;
			throw new LexerLoadError(`${sourceName}/${path}: threw while loading — ${e instanceof Error ? e.message : e}`);
		}
		return module.exports;
	};

	const exports = load(entry);
	const lexer = exports?.default ?? exports;
	const problem = validateLexerShape(lexer);
	if (problem) {
		throw new LexerLoadError(`${sourceName}: ${problem}`);
	}
	return lexer as Lexer;
}

// path is relative to the picked folder ('index.js', 'lib/tables.js')
export type PickedFile = { path: string, content: string };

// Open the OS folder browser for a lexer's folder (index.js + modules +
// palette.json). Nothing happens if the user cancels.
export function pickLexerFolder(onPick: (files: PickedFile[]) => void): void {
	const input = document.createElement('input');
	input.type = 'file';
	input.webkitdirectory = true;
	input.onchange = async () => {
		const files = Array.from(input.files ?? []);
		if (!files.length) return;
		onPick(await Promise.all(files.map(async f => ({
			// webkitRelativePath is '<picked-folder>/<path-in-folder>'
			path: f.webkitRelativePath.split('/').slice(1).join('/'),
			content: await f.text(),
		}))));
	};
	input.click();
}
