/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => LetterAPlugin,
  refreshHighlight: () => refreshHighlight
});
module.exports = __toCommonJS(main_exports);
var import_obsidian5 = require("obsidian");
var import_state = require("@codemirror/state");
var import_view = require("@codemirror/view");

// settings/settings.ts
var import_obsidian4 = require("obsidian");

// settings/pallet.ts
var import_obsidian = require("obsidian");

// settings/base_settings.ts
var BaseSettingsTab = class {
  // `refresh` re-renders the whole settings pane, so a change in one tab
  // (e.g. adding/removing a palette colour) is reflected in the others.
  constructor(plugin, containerEl, refresh) {
    this.plugin = plugin;
    this.containerEl = containerEl;
    this.refresh = refresh;
  }
};

// settings/pallet.ts
var default_colours = [
  { id: "global-red", name: "Red", value: "#ff0000", isCustom: false },
  { id: "global-green", name: "Green", value: "#00ff00", isCustom: false },
  { id: "global-blue", name: "Blue", value: "#0000ff", isCustom: false },
  { id: "global-yellow", name: "Yellow", value: "#ffff00", isCustom: false },
  { id: "global-cyan", name: "Cyan", value: "#00ffff", isCustom: false },
  { id: "global-magenta", name: "Magenta", value: "#ff00ff", isCustom: false }
];
var PaletteSettingsTab = class extends BaseSettingsTab {
  display() {
    const { containerEl, plugin } = this;
    containerEl.createEl("h2", { text: "Default Colors" });
    const defaultColorsDiv = containerEl.createDiv();
    const colorsHeader = new import_obsidian.Setting(defaultColorsDiv).setName("Palette").setDesc("Manage default colors").setClass("tokens-colors-header");
    const colorsContainer = defaultColorsDiv.createDiv();
    colorsHeader.addExtraButton((btn) => {
      const key = "palette";
      const apply = (expanded) => {
        if (expanded) {
          colorsContainer.show();
          btn.setIcon("chevron-down").setTooltip("Collapse");
          colorsHeader.settingEl.removeClass("collapsed");
          plugin.expandedSections.add(key);
        } else {
          colorsContainer.hide();
          btn.setIcon("chevron-right").setTooltip("Expand");
          colorsHeader.settingEl.addClass("collapsed");
          plugin.expandedSections.delete(key);
        }
      };
      apply(plugin.expandedSections.has(key));
      const toggle = () => apply(!colorsContainer.isShown());
      btn.onClick(toggle);
      colorsHeader.settingEl.addEventListener(
        "dblclick",
        (event) => {
          const target = event.target;
          if (target.closest("input, .checkbox-container, .extra-setting-button")) {
            return;
          }
          toggle();
        }
      );
    });
    const colorListContainer = colorsContainer.createDiv();
    const renderColors = () => {
      colorListContainer.empty();
      plugin.settings.coloursPallete.forEach((colorValue, index) => {
        const setting = new import_obsidian.Setting(colorListContainer);
        if (colorValue.isCustom) {
          setting.addText((text) => {
            text.setValue(colorValue.name).onChange(async (value) => {
              plugin.settings.coloursPallete[index].name = value;
              await plugin.saveSettings();
            });
            setting.nameEl.appendChild(text.inputEl);
            const initialName = colorValue.name;
            text.inputEl.addEventListener("blur", () => {
              if (colorValue.name !== initialName)
                this.refresh();
            });
          });
        } else {
          setting.setName(colorValue.name);
        }
        setting.addColorPicker((color) => {
          color.setValue(colorValue.value).onChange(async (value) => {
            plugin.settings.coloursPallete[index].value = value;
            await plugin.saveSettings();
            this.refresh();
          });
        }).setClass("tokens-colors-element");
        if (colorValue.isCustom) {
          setting.addExtraButton((btn) => {
            const inUse = this.colourInUse(colorValue);
            btn.setIcon("trash").setTooltip(inUse ? "In use by a token type \u2014 cannot delete" : "Remove").onClick(async () => {
              if (this.colourInUse(colorValue)) {
                new import_obsidian.Notice(`Cannot delete "${colorValue.name}": it is in use by a token type.`);
                return;
              }
              plugin.settings.coloursPallete.splice(index, 1);
              await plugin.saveSettings();
              this.refresh();
            });
          });
        }
      });
    };
    renderColors();
    new import_obsidian.Setting(colorsContainer).setName("Add Color").addButton((btn) => {
      btn.setButtonText("Add").onClick(async () => {
        plugin.settings.coloursPallete.push({ id: newColourId(), name: "New Color", value: "#ffffff", isCustom: true });
        await plugin.saveSettings();
        this.refresh();
      });
    }).setClass("tokens-colors-footer");
  }
  // a colour is "in use" if any lexer's token mapping references its id.
  // Includes disabled lexers.
  colourInUse(colour) {
    return Object.values(this.plugin.settings.lexersSettings).some((ls) => Object.values(ls.colourMappings).includes(colour.id));
  }
};

// settings/lexers.ts
var import_obsidian3 = require("obsidian");

// settings/modals.ts
var import_obsidian2 = require("obsidian");
var ColourNameModal = class extends import_obsidian2.Modal {
  constructor(app, value, taken, onSubmit, onCancel) {
    super(app);
    this.value = value;
    this.taken = taken;
    this.onSubmit = onSubmit;
    this.onCancel = onCancel;
    this.name = "";
    this.submitted = false;
  }
  onOpen() {
    this.titleEl.setText("Name this colour");
    new import_obsidian2.Setting(this.contentEl).setName("Colour name").addText((text) => text.setPlaceholder(this.value).onChange((v) => this.name = v));
    const error = this.contentEl.createDiv({ cls: "setting-item-description" });
    error.style.color = "var(--text-error)";
    new import_obsidian2.Setting(this.contentEl).addButton((btn) => btn.setButtonText("Add").setCta().onClick(() => {
      const name = this.name.trim() || this.value;
      if (this.taken.some((t) => t.toLowerCase() === name.toLowerCase())) {
        error.setText(`A colour named "${name}" already exists.`);
        return;
      }
      this.submitted = true;
      this.close();
      this.onSubmit(name);
    }));
  }
  onClose() {
    this.contentEl.empty();
    if (!this.submitted)
      this.onCancel();
  }
};
var RestoreDefaultsModal = class extends import_obsidian2.Modal {
  constructor(app, lexerName, onRestore) {
    super(app);
    this.lexerName = lexerName;
    this.onRestore = onRestore;
  }
  onOpen() {
    this.titleEl.setText(`Restore "${this.lexerName}" colours to defaults`);
    this.contentEl.createEl("p", {
      text: "Supplied colour values and all token mappings will be reset to the lexer's defaults. The global palette, the extension name and the enabled state are not touched."
    });
    this.contentEl.createEl("p", {
      text: "What should happen to the custom colours you added to this lexer?"
    });
    new import_obsidian2.Setting(this.contentEl).addButton((btn) => btn.setButtonText("Keep them").setCta().onClick(() => {
      this.close();
      this.onRestore(true);
    })).addButton((btn) => btn.setButtonText("Delete them").setWarning().onClick(() => {
      this.close();
      this.onRestore(false);
    })).addButton((btn) => btn.setButtonText("Cancel").onClick(() => this.close()));
  }
  onClose() {
    this.contentEl.empty();
  }
};
var CopyCollisionModal = class extends import_obsidian2.Modal {
  constructor(app, existingName, taken, onDone) {
    super(app);
    this.taken = taken;
    this.onDone = onDone;
    this.name = existingName;
  }
  onOpen() {
    this.titleEl.setText("Name already in the global palette");
    this.contentEl.createEl("p", {
      text: `A global colour named "${this.name}" already exists. Override its value, or add this colour under a new name.`
    });
    new import_obsidian2.Setting(this.contentEl).setName("New name").addText((text) => text.setValue(this.name).onChange((v) => this.name = v));
    const error = this.contentEl.createDiv({ cls: "setting-item-description" });
    error.style.color = "var(--text-error)";
    new import_obsidian2.Setting(this.contentEl).addButton((btn) => btn.setButtonText("Override existing").setWarning().onClick(() => {
      this.close();
      this.onDone("override");
    })).addButton((btn) => btn.setButtonText("Add with new name").setCta().onClick(() => {
      const name = this.name.trim();
      if (!name || this.taken.some((t) => t.toLowerCase() === name.toLowerCase())) {
        error.setText(`"${name}" is already taken \u2014 pick another name or override.`);
        return;
      }
      this.close();
      this.onDone("rename", name);
    }));
  }
  onClose() {
    this.contentEl.empty();
  }
};
var PrivatePaletteModal = class extends import_obsidian2.Modal {
  constructor(plugin, lexerSettings, refresh) {
    super(plugin.app);
    this.plugin = plugin;
    this.lexerSettings = lexerSettings;
    this.refresh = refresh;
  }
  onOpen() {
    this.render();
  }
  render() {
    const { contentEl, lexerSettings } = this;
    contentEl.empty();
    this.titleEl.setText(`"${lexerSettings.extention}" private palette`);
    if (!lexerSettings.privatePool.length) {
      contentEl.createEl("p", { text: "This lexer has no private colours." });
      return;
    }
    for (const colour of lexerSettings.privatePool) {
      const row = new import_obsidian2.Setting(contentEl).setName(colour.name).setDesc(colour.isCustom ? "Custom colour" : "Supplied by the lexer");
      row.addColorPicker((picker) => picker.setValue(colour.value).onChange(async (value) => {
        colour.value = value;
        await this.plugin.saveSettings();
        this.refresh();
      }));
      row.addExtraButton((btn) => btn.setIcon("copy").setTooltip("Copy to global palette").onClick(() => this.copyToGlobal(colour)));
      if (colour.isCustom) {
        const inUse = this.inUse(colour);
        row.addExtraButton((btn) => btn.setIcon("trash").setTooltip(inUse ? "In use by a token type \u2014 cannot delete" : "Delete").onClick(async () => {
          if (this.inUse(colour)) {
            new import_obsidian2.Notice(`Cannot delete "${colour.name}": it is in use by a token type.`);
            return;
          }
          const pool = this.lexerSettings.privatePool;
          pool.splice(pool.indexOf(colour), 1);
          await this.plugin.saveSettings();
          this.refresh();
          this.render();
        }));
      }
    }
  }
  inUse(colour) {
    return Object.values(this.lexerSettings.colourMappings).includes(colour.id);
  }
  copyToGlobal(colour) {
    const palette = this.plugin.settings.coloursPallete;
    const clash = palette.find((c) => c.name.toLowerCase() === colour.name.toLowerCase());
    if (!clash) {
      palette.push({ id: newColourId(), name: colour.name, value: colour.value, isCustom: true });
      void this.plugin.saveSettings().then(() => this.refresh());
      new import_obsidian2.Notice(`"${colour.name}" added to the global palette.`);
      return;
    }
    new CopyCollisionModal(this.app, clash.name, palette.map((c) => c.name), async (action, name) => {
      if (action === "override") {
        clash.value = colour.value;
        new import_obsidian2.Notice(`Global "${clash.name}" updated.`);
      } else {
        palette.push({ id: newColourId(), name, value: colour.value, isCustom: true });
        new import_obsidian2.Notice(`"${name}" added to the global palette.`);
      }
      await this.plugin.saveSettings();
      this.refresh();
    }).open();
  }
  onClose() {
    this.contentEl.empty();
  }
};

// lexing/reconcile.ts
function validateLexer(lexer) {
  const warnings = [];
  const seen = /* @__PURE__ */ new Set();
  for (const colour of lexer.requiredColours) {
    const key = colour.name.toLowerCase();
    if (seen.has(key)) {
      warnings.push(`duplicate required colour name "${colour.name}"`);
    }
    seen.add(key);
  }
  for (const [tokenType, colourName] of Object.entries(lexer.colourMapping)) {
    if (!lexer.requiredColours.some((c) => c.name === colourName)) {
      warnings.push(`token type "${tokenType}" maps to undeclared colour "${colourName}"`);
    }
  }
  return warnings;
}
function defaultMappings(lexer, pool) {
  const mappings = {};
  for (const [tokenType, colourName] of Object.entries(lexer.colourMapping)) {
    const colour = pool.find((c) => !c.isCustom && c.name === colourName);
    if (colour) {
      mappings[tokenType] = colour.id;
    }
  }
  return mappings;
}
function seedLexerSettings(lexer) {
  const pool = lexer.requiredColours.map((c) => ({ id: newColourId(), name: c.name, value: c.value, isCustom: false }));
  return new LexerSettings2(lexer.id, lexer.name, pool, defaultMappings(lexer, pool));
}
function reconcileLexerSettings(settings, lexer) {
  for (const declared of lexer.requiredColours) {
    if (!settings.privatePool.some((c) => !c.isCustom && c.name === declared.name)) {
      settings.privatePool.push({ id: newColourId(), name: declared.name, value: declared.value, isCustom: false });
    }
  }
  const referenced = new Set(Object.values(settings.colourMappings));
  settings.privatePool = settings.privatePool.filter((c) => c.isCustom || lexer.requiredColours.some((d) => d.name === c.name) || referenced.has(c.id));
  const defaults = defaultMappings(lexer, settings.privatePool);
  for (const [tokenType, colourId] of Object.entries(defaults)) {
    if (!(tokenType in settings.colourMappings)) {
      settings.colourMappings[tokenType] = colourId;
    }
  }
}
function restoreLexerDefaults(settings, lexer, keepCustomColours) {
  for (const colour of settings.privatePool) {
    if (colour.isCustom)
      continue;
    const declared = lexer.requiredColours.find((d) => d.name === colour.name);
    if (declared) {
      colour.value = declared.value;
    }
  }
  for (const declared of lexer.requiredColours) {
    if (!settings.privatePool.some((c) => !c.isCustom && c.name === declared.name)) {
      settings.privatePool.push({ id: newColourId(), name: declared.name, value: declared.value, isCustom: false });
    }
  }
  settings.privatePool = settings.privatePool.filter((c) => c.isCustom ? keepCustomColours : lexer.requiredColours.some((d) => d.name === c.name));
  settings.colourMappings = defaultMappings(lexer, settings.privatePool);
}

// lexing/loader.ts
var IMPORTED_LEXERS_DIR = "imported_lexers";
var LEXER_API_DTS = `// generated by the syntax-highlighting plugin \u2014 describes what a lexer
// file must export. Reference it from your lexer with:
//   /** @type {import('./lexer-api').Lexer} */
//   module.exports = { ... };

export type Token = { text: string; type: string };

export type DeclaredColour = { name: string; value: string };

export interface Lexer {
	/** stable namespaced identity, e.g. 'alfred.nasm' \u2014 never change between versions */
	id: string;
	/** bump when token types / colours change */
	version?: number;
	/** display name and the default code-block tag (the \`\`\`name fence) */
	name: string;
	/** every colour this lexer uses \u2014 names are frozen once shipped */
	requiredColours: DeclaredColour[];
	/** token type -> the name of a colour declared in requiredColours */
	colourMapping: Record<string, string>;
	tokenize(input: string): Token[];
}
`;
function validateLexerShape(obj) {
  if (!obj || typeof obj !== "object")
    return "module.exports is not an object";
  if (typeof obj.id !== "string" || !obj.id)
    return 'missing string field "id"';
  if (typeof obj.name !== "string" || !obj.name)
    return 'missing string field "name"';
  if (obj.version !== void 0 && typeof obj.version !== "number")
    return '"version" must be a number';
  if (!Array.isArray(obj.requiredColours))
    return 'missing array field "requiredColours"';
  for (const colour of obj.requiredColours) {
    if (!colour || typeof colour.name !== "string" || typeof colour.value !== "string") {
      return "requiredColours entries must be { name: string, value: string }";
    }
  }
  if (!obj.colourMapping || typeof obj.colourMapping !== "object" || Array.isArray(obj.colourMapping)) {
    return 'missing object field "colourMapping"';
  }
  for (const [tokenType, colourName] of Object.entries(obj.colourMapping)) {
    if (typeof colourName !== "string") {
      return `colourMapping["${tokenType}"] must be a colour name (string)`;
    }
  }
  if (typeof obj.tokenize !== "function")
    return 'missing function "tokenize"';
  return null;
}
function evaluateLexerSource(code, sourceName) {
  var _a, _b;
  const module2 = { exports: {} };
  let factory;
  try {
    factory = new Function("module", "exports", code);
  } catch (e) {
    throw new Error(`${sourceName}: syntax error \u2014 ${e instanceof Error ? e.message : e}`);
  }
  try {
    factory(module2, module2.exports);
  } catch (e) {
    throw new Error(`${sourceName}: threw while loading \u2014 ${e instanceof Error ? e.message : e}`);
  }
  const lexer = (_b = (_a = module2.exports) == null ? void 0 : _a.default) != null ? _b : module2.exports;
  const problem = validateLexerShape(lexer);
  if (problem) {
    throw new Error(`${sourceName}: ${problem}`);
  }
  return lexer;
}
function pickJsFile(onPick) {
  const input = document.createElement("input");
  input.type = "file";
  input.accept = ".js";
  input.onchange = async () => {
    var _a;
    const file = (_a = input.files) == null ? void 0 : _a[0];
    if (!file)
      return;
    onPick(await file.text(), file.name);
  };
  input.click();
}

// settings/lexers.ts
var LexerSettingsTab = class extends BaseSettingsTab {
  display() {
    const { containerEl, plugin } = this;
    containerEl.createEl("h2", { text: "Lexers Settings" });
    new import_obsidian3.Setting(containerEl).setName("Imported lexers").setDesc("Import a .js lexer file, or reload the imported lexers folder").addButton((btn) => btn.setButtonText("Import").setCta().onClick(() => {
      pickJsFile(async (code, fileName) => {
        let imported;
        try {
          imported = evaluateLexerSource(code, fileName);
        } catch (e) {
          new import_obsidian3.Notice(`${e instanceof Error ? e.message : e}`);
          return;
        }
        const clash = Object.entries(plugin.lexersByUuid).find(([, l]) => l.id === imported.id);
        if (clash) {
          const clashPath = plugin.lexerSourcePaths[clash[0]];
          if (!clashPath || !clashPath.endsWith(`/${fileName}`)) {
            new import_obsidian3.Notice(`Lexer id "${imported.id}" is already installed \u2014 use its Update option instead.`);
            return;
          }
        }
        await plugin.app.vault.adapter.write(`${plugin.importedLexersDir()}/${fileName}`, code);
        await plugin.loadLexers();
        this.refresh();
        new import_obsidian3.Notice(`Imported "${imported.name}" (${imported.id})`);
      });
    })).addButton((btn) => btn.setButtonText("Reload").onClick(async () => {
      await plugin.loadLexers();
      this.refresh();
      new import_obsidian3.Notice("Lexers reloaded");
    }));
    for (const [uuid, lexerSettings] of Object.entries(plugin.settings.lexersSettings)) {
      const lexer = plugin.lexersByUuid[uuid];
      if (!lexer)
        continue;
      const lexerDiv = containerEl.createDiv();
      const header = new import_obsidian3.Setting(lexerDiv).setName(lexerSettings.extention).addText((text) => {
        const container = text.inputEl.parentElement;
        if (container) {
          container.prepend(createSpan({ text: "Code-Block Extension: " }));
        }
        text.setValue(lexerSettings.extention).onChange(async (value) => {
          const prev_value = lexerSettings.extention;
          const registered = plugin.lexers[prev_value];
          delete plugin.lexers[prev_value];
          lexerSettings.extention = value;
          plugin.lexers[value] = registered;
          await plugin.saveSettings();
        });
      }).addToggle((toggle) => {
        toggle.setValue(lexerSettings.enabled).onChange(async (value) => {
          lexerSettings.enabled = value;
          await this.plugin.saveSettings();
        });
      }).setClass("tokens-colors-header");
      header.addExtraButton((btn) => {
        btn.setIcon("more-vertical").setTooltip("More options");
        btn.extraSettingsEl.addEventListener("click", (evt) => {
          const menu = new import_obsidian3.Menu();
          menu.addItem((item) => item.setTitle("Restore default colours").setIcon("rotate-ccw").onClick(() => {
            new RestoreDefaultsModal(plugin.app, lexerSettings.extention, async (keepCustomColours) => {
              restoreLexerDefaults(lexerSettings, lexer, keepCustomColours);
              await plugin.saveSettings();
              this.refresh();
            }).open();
          }));
          menu.addItem((item) => item.setTitle("View private palette").setIcon("palette").onClick(() => {
            new PrivatePaletteModal(plugin, lexerSettings, () => this.refresh()).open();
          }));
          const sourcePath = plugin.lexerSourcePaths[uuid];
          if (sourcePath) {
            menu.addItem((item) => item.setTitle("Update lexer").setIcon("upload").onClick(() => {
              pickJsFile(async (code, fileName) => {
                let updated;
                try {
                  updated = evaluateLexerSource(code, fileName);
                } catch (e) {
                  new import_obsidian3.Notice(`${e instanceof Error ? e.message : e}`);
                  return;
                }
                if (updated.id !== lexer.id) {
                  new import_obsidian3.Notice(`Id mismatch: the file declares "${updated.id}" but this lexer is "${lexer.id}". To install it as a new lexer, use Import.`);
                  return;
                }
                await plugin.app.vault.adapter.write(sourcePath, code);
                await plugin.loadLexers();
                this.refresh();
                new import_obsidian3.Notice(`"${lexerSettings.extention}" updated to ${updated.version !== void 0 ? `v${updated.version}` : "the new file"}`);
              });
            }));
          }
          menu.showAtMouseEvent(evt);
        });
      });
      const tokensDiv = lexerDiv.createDiv();
      header.addExtraButton((btn) => {
        const key = `lexer:${uuid}`;
        const apply = (expanded) => {
          if (expanded) {
            tokensDiv.show();
            btn.setIcon("chevron-down").setTooltip("Collapse");
            header.settingEl.removeClass("collapsed");
            plugin.expandedSections.add(key);
          } else {
            tokensDiv.hide();
            btn.setIcon("chevron-right").setTooltip("Expand");
            header.settingEl.addClass("collapsed");
            plugin.expandedSections.delete(key);
          }
        };
        apply(plugin.expandedSections.has(key));
        const toggle = () => apply(!tokensDiv.isShown());
        btn.onClick(toggle);
        header.settingEl.addEventListener("dblclick", (event) => {
          const target = event.target;
          if (target.closest("input, .checkbox-container, .extra-setting-button")) {
            return;
          }
          toggle();
        });
      });
      const palette = plugin.settings.coloursPallete;
      const pool = lexerSettings.privatePool;
      const mappings = lexerSettings.colourMappings;
      const resolve = (id) => plugin.resolveColour(lexerSettings, id);
      const entries = Object.entries(mappings);
      entries.forEach(([tokenType, mappedId], index) => {
        let colorComp;
        let dropdownComp;
        let programmatic = false;
        const cssClass = index === entries.length - 1 ? "tokens-colors-footer" : "tokens-colors-element";
        const current = resolve(mappedId);
        new import_obsidian3.Setting(tokensDiv).setName(`${tokenType} Color`).setClass(cssClass).addDropdown((dropdown) => {
          dropdownComp = dropdown;
          dropdown.addOption("custom", "Custom Colour");
          const addGroup = (label, colours) => {
            if (!colours.length)
              return;
            const group = dropdown.selectEl.createEl("optgroup", { attr: { label } });
            for (const c of colours) {
              group.createEl("option", { value: c.id, text: c.name });
            }
          };
          addGroup("Global palette", palette);
          addGroup("Private colours", pool);
          dropdown.setValue(current ? current.id : "custom");
          dropdown.onChange(async (id) => {
            var _a, _b;
            if (id === "custom") {
              colorComp.setDisabled(false);
              colorComp.colorPickerEl.click();
              return;
            }
            mappings[tokenType] = id;
            programmatic = true;
            colorComp.setValue((_b = (_a = resolve(id)) == null ? void 0 : _a.value) != null ? _b : "#ffffff");
            programmatic = false;
            colorComp.setDisabled(true);
            await plugin.saveSettings();
          });
        }).addColorPicker((color) => {
          var _a;
          colorComp = color;
          color.setValue((_a = current == null ? void 0 : current.value) != null ? _a : "#ffffff").setDisabled(true).onChange((value) => {
            if (programmatic)
              return;
            if (dropdownComp.getValue() !== "custom")
              return;
            const previousId = mappings[tokenType];
            new ColourNameModal(plugin.app, value, pool.map((c) => c.name), async (name) => {
              const colour = { id: newColourId(), name, value, isCustom: true };
              pool.push(colour);
              mappings[tokenType] = colour.id;
              await plugin.saveSettings();
              this.refresh();
            }, () => {
              var _a2, _b;
              dropdownComp.setValue(previousId);
              programmatic = true;
              colorComp.setValue((_b = (_a2 = resolve(previousId)) == null ? void 0 : _a2.value) != null ? _b : "#ffffff");
              programmatic = false;
              colorComp.setDisabled(true);
            }).open();
          });
        });
      });
    }
    ;
  }
};

// settings/settings.ts
var LetterASettingTab = class extends import_obsidian4.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    const refresh = () => this.display();
    containerEl.createEl("h2", { text: "Highlighter Settings" });
    new PaletteSettingsTab(this.plugin, containerEl, refresh).display();
    new LexerSettingsTab(this.plugin, containerEl, refresh).display();
  }
};
function newColourId() {
  return crypto.randomUUID();
}
var LexerSettings2 = class {
  constructor(lexerId, extention, privatePool, colourMappings, enabled) {
    this.lexerId = lexerId;
    this.extention = extention;
    this.privatePool = privatePool;
    this.colourMappings = colourMappings;
    this.enabled = enabled != null ? enabled : true;
  }
};
var DEFAULT_SETTINGS = {
  coloursPallete: default_colours,
  lexersSettings: {}
};

// lexing/api.ts
var lexers = [];

// lexing/lexers/index.ts
var lexers_exports = {};

// main.ts
var refreshHighlight = import_state.StateEffect.define();
var LetterAPlugin = class extends import_obsidian5.Plugin {
  constructor() {
    super(...arguments);
    this.settings = DEFAULT_SETTINGS;
    this.lexers = {};
    // keyed by code-block extension (render path)
    this.lexersByUuid = {};
    // keyed by settings uuid (settings path)
    // source file of each imported lexer, keyed by settings uuid (built-ins absent)
    this.lexerSourcePaths = {};
    // transient (not persisted) — which settings sections are expanded, so a
    // re-render of the settings pane preserves the user's open/closed sections
    this.expandedSections = /* @__PURE__ */ new Set();
  }
  async onload() {
    await this.loadSettings();
    await this.loadLexers();
    this.registerEditorExtension(this.buildEditorExtension());
    this.addSettingTab(new LetterASettingTab(this.app, this));
    this.addCommand({
      id: "reload-lexers",
      name: "Reload lexers",
      callback: async () => {
        await this.loadLexers();
        new import_obsidian5.Notice("Lexers reloaded");
      }
    });
  }
  importedLexersDir() {
    return `${this.manifest.dir}/${IMPORTED_LEXERS_DIR}`;
  }
  // scan imported_lexers/*.js; a file that fails to load is skipped with a
  // notice and its stored settings stay untouched until it loads again
  async scanFileLexers() {
    const adapter = this.app.vault.adapter;
    const dir = this.importedLexersDir();
    if (!await adapter.exists(dir)) {
      await adapter.mkdir(dir);
    }
    await adapter.write(`${dir}/lexer-api.d.ts`, LEXER_API_DTS);
    const fileLexers = [];
    for (const path of (await adapter.list(dir)).files) {
      if (!path.endsWith(".js"))
        continue;
      try {
        const code = await adapter.read(path);
        fileLexers.push({ lexer: evaluateLexerSource(code, path), path });
      } catch (e) {
        console.warn("[lexer file]", e);
        new import_obsidian5.Notice(`Failed to load lexer: ${e instanceof Error ? e.message : e}`);
      }
    }
    return fileLexers;
  }
  async loadLexers() {
    var _a;
    this.lexers = {};
    this.lexersByUuid = {};
    this.lexerSourcePaths = {};
    const seenIds = /* @__PURE__ */ new Set();
    const fileLexers = await this.scanFileLexers();
    const allLexers = [
      ...lexers.map((lexer) => ({ lexer })),
      ...fileLexers
    ];
    for (const { lexer, path } of allLexers) {
      if (seenIds.has(lexer.id)) {
        console.warn(`[lexer ${lexer.id}] duplicate lexer id \u2014 skipping ${path != null ? path : "(built-in)"}`);
        new import_obsidian5.Notice(`Lexer id "${lexer.id}" is already in use \u2014 skipping ${path != null ? path : "a duplicate"}.`);
        continue;
      }
      seenIds.add(lexer.id);
      for (const warning of validateLexer(lexer)) {
        console.warn(`[lexer ${lexer.id}] ${warning}`);
      }
      const existing = Object.entries(this.settings.lexersSettings).find(([, ls]) => ls.lexerId === lexer.id);
      const uuid = (_a = existing == null ? void 0 : existing[0]) != null ? _a : crypto.randomUUID();
      let lexerSettings = existing == null ? void 0 : existing[1];
      if (lexerSettings) {
        reconcileLexerSettings(lexerSettings, lexer);
      } else {
        lexerSettings = seedLexerSettings(lexer);
      }
      this.settings.lexersSettings[uuid] = lexerSettings;
      this.lexers[lexerSettings.extention] = { lexer, uuid };
      this.lexersByUuid[uuid] = lexer;
      if (path) {
        this.lexerSourcePaths[uuid] = path;
      }
    }
    await this.saveSettings();
  }
  // resolve a token mapping's colour id against the global palette and the
  // owning lexer's private pool (scope is derived, not stored)
  resolveColour(lexerSettings, colourId) {
    var _a;
    if (!colourId)
      return void 0;
    return (_a = this.settings.coloursPallete.find((c) => c.id === colourId)) != null ? _a : lexerSettings.privatePool.find((c) => c.id === colourId);
  }
  async loadSettings() {
    console.log("loading data");
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
    this.settings.coloursPallete = this.settings.coloursPallete.map((c) => ({ ...c }));
  }
  async saveSettings() {
    console.log("Saving settings:", this.settings);
    await this.saveData(this.settings);
    this.refreshEditors();
  }
  refreshEditors() {
    this.app.workspace.getLeavesOfType("markdown").forEach((leaf) => {
      var _a;
      const view = leaf.view;
      const cm = (_a = view.editor) == null ? void 0 : _a.cm;
      cm == null ? void 0 : cm.dispatch({ effects: refreshHighlight.of(null) });
    });
  }
  buildEditorExtension() {
    const plugin = this;
    return import_view.ViewPlugin.fromClass(
      class {
        constructor(view) {
          this.decorations = this.buildDecorations(view);
        }
        update(update) {
          if (update.docChanged || update.viewportChanged || update.transactions.some((tr) => tr.effects.some((e) => e.is(refreshHighlight)))) {
            this.decorations = this.buildDecorations(update.view);
          }
        }
        buildDecorations(view) {
          var _a;
          const builder = new import_state.RangeSetBuilder();
          class BWidget extends import_view.WidgetType {
            constructor(text, colour) {
              super();
              this.text = text;
              this.colour = colour;
            }
            toDOM(view2) {
              const span = document.createElement("span");
              span.textContent = this.text;
              span.style.color = this.colour.value;
              span.style.fontWeight = "bold";
              return span;
            }
          }
          const file_text = view.state.doc.toString();
          const code_block_regex2 = new RegExp(`(\`\`\`(\\w+)
)([\\s\\S]*?)(\`\`\`)`, "gmi");
          let code_block;
          while ((code_block = code_block_regex2.exec(file_text)) !== null) {
            const HEADER_ID = 1;
            const EXTENTION_ID = 2;
            const BLOCK_TEXT_ID = 3;
            const FOOTER_ID = 4;
            const registered = plugin.lexers[code_block[EXTENTION_ID]];
            if (!registered) {
              continue;
            }
            const lexer = registered.lexer;
            const lexerSettings = plugin.settings.lexersSettings[registered.uuid];
            if (!lexerSettings.enabled) {
              continue;
            }
            const start_of_code_block = code_block.index + code_block[HEADER_ID].length;
            const textInsideCodeBlock = code_block[BLOCK_TEXT_ID];
            console.log("found code block: " + textInsideCodeBlock);
            let last_index = 0;
            let tokens;
            try {
              tokens = lexer.tokenize(textInsideCodeBlock);
            } catch (e) {
              console.warn(`[lexer ${lexer.id}] tokenize threw:`, e);
              continue;
            }
            for (const token of tokens) {
              if (!token || typeof token.text !== "string" || typeof token.type !== "string") {
                console.warn(`[lexer ${lexer.id}] skipping malformed token`, token);
                continue;
              }
              console.log("token found " + token.text + " token type: " + token.type);
              const relevant_part = textInsideCodeBlock.slice(last_index);
              const token_index = relevant_part.indexOf(token.text);
              for (let i = 0; i < token.text.length; i++) {
                const colour = (_a = plugin.resolveColour(lexerSettings, lexerSettings.colourMappings[token.type])) != null ? _a : default_colours[0];
                const replaceDecoration = import_view.Decoration.replace({
                  widget: new BWidget(relevant_part[token_index + i], colour)
                });
                const matchPos = start_of_code_block + last_index + token_index;
                builder.add(matchPos + i, matchPos + i + 1, replaceDecoration);
              }
              last_index += token_index + token.text.length;
            }
          }
          return builder.finish();
        }
      },
      {
        decorations: (v) => v.decorations
      }
    );
  }
};
