/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => LetterAPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");
var import_state = require("@codemirror/state");
var import_view = require("@codemirror/view");
var DEFAULT_SETTINGS = {
  highlightColor: "#ff0000"
  // Default Red
};
var LetterAPlugin = class extends import_obsidian.Plugin {
  async onload() {
    await this.loadSettings();
    this.registerEditorExtension(this.buildEditorExtension());
    this.addSettingTab(new LetterASettingTab(this.app, this));
    this.updateColorStyle();
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
    this.updateColorStyle();
    this.app.workspace.updateOptions();
  }
  updateColorStyle() {
    document.body.style.setProperty("--letter-a-highlight-color", this.settings.highlightColor);
  }
  buildEditorExtension() {
    return import_view.ViewPlugin.fromClass(
      class {
        constructor(view) {
          this.decorations = this.buildDecorations(view);
        }
        update(update) {
          if (update.docChanged || update.viewportChanged) {
            this.decorations = this.buildDecorations(update.view);
          }
        }
        buildDecorations(view) {
          const builder = new import_state.RangeSetBuilder();
          class BWidget extends import_view.WidgetType {
            toDOM(view2) {
              const span = document.createElement("span");
              span.textContent = "c";
              span.className = "letter-a-highlight";
              return span;
            }
          }
          const replaceDecoration = import_view.Decoration.replace({
            widget: new BWidget()
          });
          for (const { from, to } of view.visibleRanges) {
            const text = view.state.sliceDoc(from, to);
            const regex = /a/g;
            let match;
            while ((match = regex.exec(text)) !== null) {
              const matchPos = from + match.index;
              builder.add(matchPos, matchPos + 1, replaceDecoration);
            }
          }
          return builder.finish();
        }
      },
      {
        decorations: (v) => v.decorations
      }
    );
  }
};
var LetterASettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: 'Letter "a" Highlighter Settings' });
    new import_obsidian.Setting(containerEl).setName("Highlight Color").setDesc('Choose the color for the letter "a" inside "a" code blocks.').addColorPicker(
      (color) => color.setValue(this.plugin.settings.highlightColor).onChange(async (value) => {
        this.plugin.settings.highlightColor = value;
        await this.plugin.saveSettings();
      })
    );
  }
};
