/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  Colour: () => Colour,
  default: () => LetterAPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian2 = require("obsidian");
var import_state = require("@codemirror/state");
var import_view = require("@codemirror/view");

// settings/settings.ts
var import_obsidian = require("obsidian");

// lexing/lexers/index.ts
var lexers_exports = {};
__export(lexers_exports, {
  ExampleLexer: () => ExampleLexer,
  TestLexer: () => TestLexer
});

// lexing/api.ts
var lexers = [];

// lexing/lexers/example.ts
var ExampleLexer = class {
  getExtention() {
    return "example";
  }
  getAvailableToeknTypes() {
    return ["example", "example2"];
  }
  tokenize(text) {
    const target = /\w+/gi;
    let match;
    const tokens = [];
    while ((match = target.exec(text)) !== null) {
      tokens.push({
        text: match[0],
        type: "example"
      });
    }
    return tokens;
  }
};
lexers.push(new ExampleLexer());

// lexing/lexers/test.ts
var TestLexer = class {
  getExtention() {
    return "test";
  }
  getAvailableToeknTypes() {
    return ["test", "test2"];
  }
  tokenize(text) {
    const target = /\w+/gi;
    let match;
    const tokens = [];
    while ((match = target.exec(text)) !== null) {
      tokens.push({
        text: match[0],
        type: "test"
      });
    }
    return tokens;
  }
};
lexers.push(new TestLexer());

// settings/settings.ts
var LetterASettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "Highlighter Settings" });
    new import_obsidian.Setting(containerEl).setName("Highlight Color").setDesc('Choose the color for the letter "a" inside "a" code blocks.').addColorPicker(
      (color) => color.setValue(this.plugin.settings.highlightColor).onChange(async (value) => {
        this.plugin.settings.highlightColor = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Code Extension").setDesc("The code block extension to look for. (regex syntax)").addText(
      (text) => text.setValue(this.plugin.settings.codeExtension).onChange(async (value) => {
        this.plugin.settings.codeExtension = value;
        await this.plugin.saveSettings();
      })
    );
    containerEl.createEl("h2", { text: "Default Colors" });
    const defaultColorsDiv = containerEl.createDiv();
    const colorsHeader = new import_obsidian.Setting(defaultColorsDiv).setName("Palette").setDesc("Manage default colors").setClass("tokens-colors-header");
    colorsHeader.settingEl.addClass("collapsed");
    const colorsContainer = defaultColorsDiv.createDiv();
    colorsContainer.hide();
    colorsHeader.addExtraButton((btn) => {
      btn.setIcon("chevron-right").setTooltip("Expand").onClick(() => {
        if (colorsContainer.isShown()) {
          colorsContainer.hide();
          btn.setIcon("chevron-right");
          btn.setTooltip("Expand");
          colorsHeader.settingEl.addClass("collapsed");
        } else {
          colorsContainer.show();
          btn.setIcon("chevron-down");
          btn.setTooltip("Collapse");
          colorsHeader.settingEl.removeClass("collapsed");
        }
      });
    });
    this.plugin.settings.defaultColors.forEach((colorValue, index) => {
      const setting = new import_obsidian.Setting(colorsContainer);
      setting.addText((text) => {
        text.setValue(colorValue.name).onChange(async (value) => {
          this.plugin.settings.defaultColors[index].name = value;
          await this.plugin.saveSettings();
        });
        setting.nameEl.appendChild(text.inputEl);
      }).addColorPicker((color) => {
        color.setValue(colorValue.value).onChange(async (value) => {
          this.plugin.settings.defaultColors[index].value = value;
          await this.plugin.saveSettings();
        });
      }).addExtraButton((btn) => {
        btn.setIcon("trash").setTooltip("Remove").onClick(async () => {
          this.plugin.settings.defaultColors.splice(index, 1);
          await this.plugin.saveSettings();
          this.display();
        });
      }).setClass("tokens-colors-element");
    });
    new import_obsidian.Setting(colorsContainer).setName("Add Color").addButton((btn) => {
      btn.setButtonText("Add").onClick(async () => {
        this.plugin.settings.defaultColors.push(new Colour("New Color", "#ffffff"));
        await this.plugin.saveSettings();
        this.display();
      });
    }).setClass("tokens-colors-footer");
    containerEl.createEl("h1", { text: "Lexers" });
    for (const lexer of lexers) {
      const lexerDiv = containerEl.createDiv();
      const header = new import_obsidian.Setting(lexerDiv).setName(lexer.getExtention()).setDesc(`extention for the ${lexer.getExtention()} lexer`).addToggle((toggle) => {
        toggle.setValue(true);
      }).setClass("tokens-colors-header");
      header.settingEl.addClass("collapsed");
      const tokensDiv = lexerDiv.createDiv();
      tokensDiv.hide();
      header.addExtraButton((btn) => {
        btn.setIcon("chevron-right").setTooltip("Expand").onClick(() => {
          if (tokensDiv.isShown()) {
            tokensDiv.hide();
            btn.setIcon("chevron-right");
            btn.setTooltip("Expand");
            header.settingEl.addClass("collapsed");
          } else {
            tokensDiv.show();
            btn.setIcon("chevron-down");
            btn.setTooltip("Collapse");
            header.settingEl.removeClass("collapsed");
          }
        });
      });
      let tokens = lexer.getAvailableToeknTypes();
      if (tokens.length === 0)
        continue;
      const last_token = tokens[tokens.length - 1];
      tokens = tokens.slice(0, -1);
      for (const token of tokens) {
        new import_obsidian.Setting(tokensDiv).setName(`${token} Color`).addColorPicker((color) => color.setValue("#ff0000")).setClass("tokens-colors-element");
      }
      new import_obsidian.Setting(tokensDiv).setName(`${last_token} Color`).addColorPicker((color) => color.setValue("#ff0000")).setClass("tokens-colors-footer");
    }
  }
};

// main.ts
var Colour = class {
  constructor(name, value) {
    this.name = name;
    this.value = value;
  }
};
var DEFAULT_SETTINGS = {
  highlightColor: "#ff0000",
  // Default Red
  codeExtension: "customCode",
  // Default code block extension to look for
  defaultColors: [
    new Colour("Red", "#ff0000"),
    new Colour("Green", "#00ff00"),
    new Colour("Blue", "#0000ff"),
    new Colour("Yellow", "#ffff00"),
    new Colour("Cyan", "#00ffff"),
    new Colour("Magenta", "#ff00ff")
  ]
};
var LetterAPlugin = class extends import_obsidian2.Plugin {
  async onload() {
    await this.loadSettings();
    this.registerEditorExtension(this.buildEditorExtension());
    this.addSettingTab(new LetterASettingTab(this.app, this));
    this.updateColorStyle();
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
    this.updateColorStyle();
    this.app.workspace.updateOptions();
  }
  updateColorStyle() {
    document.body.style.setProperty("--letter-a-highlight-color", this.settings.highlightColor);
  }
  buildEditorExtension() {
    const plugin = this;
    return import_view.ViewPlugin.fromClass(
      class {
        constructor(view) {
          this.decorations = this.buildDecorations(view);
        }
        update(update) {
          if (update.docChanged || update.viewportChanged) {
            this.decorations = this.buildDecorations(update.view);
          }
        }
        buildDecorations(view) {
          const builder = new import_state.RangeSetBuilder();
          class BWidget extends import_view.WidgetType {
            constructor(text) {
              super();
              this.text = text;
            }
            toDOM(view2) {
              const span = document.createElement("span");
              span.textContent = this.text;
              span.className = "letter-a-highlight";
              return span;
            }
          }
          for (const { from, to } of view.visibleRanges) {
            const file_text = view.state.sliceDoc(from, to);
            const code_extention = plugin.settings.codeExtension;
            const code_block_regex = new RegExp(`(\`\`\`${code_extention}
)([\\s\\S]*?)(\`\`\`)`, "gmi");
            const HEADER_ID = 1;
            const BLOCK_TEXT_ID = 2;
            const FOOTER_ID = 3;
            let code_block;
            while ((code_block = code_block_regex.exec(file_text)) !== null) {
              const start_of_code_block = from + code_block.index + code_block[HEADER_ID].length;
              const textInsideCodeBlock = code_block[BLOCK_TEXT_ID];
              const target_regex = /\w+/gi;
              let match;
              while ((match = target_regex.exec(textInsideCodeBlock)) !== null) {
                const match_content = match[0];
                const matchPos = start_of_code_block + match.index;
                const replaceDecoration = import_view.Decoration.replace({
                  widget: new BWidget(match_content)
                });
                builder.add(matchPos, matchPos + match_content.length, replaceDecoration);
              }
            }
          }
          return builder.finish();
        }
      },
      {
        decorations: (v) => v.decorations
      }
    );
  }
};
